import type { Vehicle, Lead, Client, User, KPI } from '@/types'

// Mock Users
export const mockUsers: User[] = [
    {
        id: '1',
        email: 'admin@midcar.es',
        nombre: 'Admin',
        apellidos: 'Demo',
        avatar_url: null,
        rol: 'admin',
        permisos: ['all'],
        activo: true,
        fecha_alta: '2024-01-01',
        ultimo_acceso: new Date().toISOString(),
    },
    {
        id: '2',
        email: 'maria.lopez@midcar.es',
        nombre: 'María',
        apellidos: 'López',
        avatar_url: null,
        rol: 'vendedor',
        permisos: ['crm', 'inventario_lectura', 'reportes_propios'],
        activo: true,
        fecha_alta: '2024-02-15',
        ultimo_acceso: new Date(Date.now() - 3600000).toISOString(),
    },
    {
        id: '3',
        email: 'juan.martinez@midcar.es',
        nombre: 'Juan',
        apellidos: 'Martínez',
        avatar_url: null,
        rol: 'vendedor',
        permisos: ['crm', 'inventario_lectura', 'reportes_propios'],
        activo: true,
        fecha_alta: '2024-03-10',
        ultimo_acceso: new Date(Date.now() - 7200000).toISOString(),
    },
    {
        id: '4',
        email: 'pedro.garcia@midcar.es',
        nombre: 'Pedro',
        apellidos: 'García',
        avatar_url: null,
        rol: 'mecanico',
        permisos: ['inventario_taller', 'reparaciones'],
        activo: true,
        fecha_alta: '2024-01-20',
        ultimo_acceso: new Date(Date.now() - 86400000).toISOString(),
    },
]

// Mock Vehicles
export const mockVehicles: Vehicle[] = [
    {
        id: '1',
        vin: 'WVWZZZ3CZWE123456',
        matricula: '1234 ABC',
        stock_id: 'MC-001',
        estado: 'disponible',
        destacado: true,
        en_oferta: true,
        marca: 'Volkswagen',
        modelo: 'Golf',
        version: '2.0 TDI Sport',
        año_fabricacion: 2022,
        año_matriculacion: 2022,
        tipo_motor: 'TDI',
        cilindrada: 1968,
        potencia_cv: 150,
        potencia_kw: 110,
        combustible: 'diesel',
        consumo_mixto: 4.5,
        emisiones_co2: 118,
        etiqueta_dgt: 'C',
        transmision: 'automatico',
        num_marchas: 7,
        traccion: 'Delantera',
        tipo_carroceria: 'Berlina',
        num_puertas: 5,
        num_plazas: 5,
        color_exterior: 'Gris Urano',
        color_interior: 'Negro',
        kilometraje: 45000,
        num_propietarios: 1,
        es_nacional: true,
        primera_mano: true,
        precio_compra: 18000,
        gastos_compra: 500,
        coste_reparaciones: 800,
        precio_venta: 24900,
        descuento: 500,
        margen_bruto: 5100,
        fecha_entrada_stock: '2024-10-15',
        dias_en_stock: 45,
        garantia_meses: 12,
        tipo_garantia: 'Mecánica completa',
        imagen_principal: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800',
        imagenes: [],
        equipamiento: ['abs', 'esp', 'control_traccion', 'airbags_frontales', 'isofix', 'climatizador', 'volante_multifuncion', 'sensores_parking', 'bluetooth', 'apple_carplay', 'android_auto', 'faros_led', 'luces_diurnas_led', 'cruise_control'],
        created_at: '2024-10-15T10:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        id: '2',
        vin: 'WAUZZZ4G7EN123456',
        matricula: '5678 DEF',
        stock_id: 'MC-002',
        estado: 'disponible',
        destacado: false,
        en_oferta: false,
        marca: 'Audi',
        modelo: 'A4',
        version: '35 TFSI S-Line',
        año_fabricacion: 2021,
        año_matriculacion: 2021,
        tipo_motor: 'TFSI',
        cilindrada: 1984,
        potencia_cv: 150,
        potencia_kw: 110,
        combustible: 'gasolina',
        consumo_mixto: 6.2,
        emisiones_co2: 141,
        etiqueta_dgt: 'C',
        transmision: 'automatico',
        num_marchas: 7,
        traccion: 'Delantera',
        tipo_carroceria: 'Berlina',
        num_puertas: 4,
        num_plazas: 5,
        color_exterior: 'Negro Brillante',
        color_interior: 'Cuero Negro',
        kilometraje: 52000,
        num_propietarios: 2,
        es_nacional: true,
        primera_mano: false,
        precio_compra: 22000,
        gastos_compra: 600,
        coste_reparaciones: 1200,
        precio_venta: 28900,
        descuento: 0,
        margen_bruto: 5100,
        fecha_entrada_stock: '2024-09-20',
        dias_en_stock: 70,
        garantia_meses: 12,
        tipo_garantia: 'Mecánica completa',
        imagen_principal: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
        imagenes: [],
        equipamiento: ['abs', 'esp', 'control_traccion', 'airbags_frontales', 'airbags_laterales', 'isofix', 'climatizador', 'asientos_calefactados', 'volante_multifuncion', 'sensores_parking', 'camara_trasera', 'navegador_gps', 'pantalla_tactil', 'bluetooth', 'apple_carplay', 'android_auto', 'faros_led', 'luces_diurnas_led', 'faros_adaptativos', 'cruise_control_adaptativo', 'asistente_aparcamiento'],
        created_at: '2024-09-20T10:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        id: '3',
        vin: 'WBAPH5C55BA123456',
        matricula: '9012 GHI',
        stock_id: 'MC-003',
        estado: 'reservado',
        destacado: true,
        en_oferta: false,
        marca: 'BMW',
        modelo: 'Serie 3',
        version: '320d M Sport',
        año_fabricacion: 2023,
        año_matriculacion: 2023,
        tipo_motor: 'TwinPower Turbo',
        cilindrada: 1995,
        potencia_cv: 190,
        potencia_kw: 140,
        combustible: 'diesel',
        consumo_mixto: 4.8,
        emisiones_co2: 126,
        etiqueta_dgt: 'C',
        transmision: 'automatico',
        num_marchas: 8,
        traccion: 'Trasera',
        tipo_carroceria: 'Berlina',
        num_puertas: 4,
        num_plazas: 5,
        color_exterior: 'Blanco Alpino',
        color_interior: 'Cuero Vernasca Negro',
        kilometraje: 18000,
        num_propietarios: 1,
        es_nacional: true,
        primera_mano: true,
        precio_compra: 32000,
        gastos_compra: 800,
        coste_reparaciones: 0,
        precio_venta: 42900,
        descuento: 0,
        margen_bruto: 10100,
        fecha_entrada_stock: '2024-11-01',
        dias_en_stock: 28,
        garantia_meses: 24,
        tipo_garantia: 'BMW Premium Selection',
        imagen_principal: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
        imagenes: [],
        equipamiento: ['abs', 'esp', 'control_traccion', 'airbags_frontales', 'airbags_laterales', 'airbags_cortina', 'isofix', 'asistente_frenado', 'detector_angulo_muerto', 'alerta_cambio_carril', 'climatizador', 'asientos_calefactados', 'asientos_electricos', 'asientos_memoria', 'volante_multifuncion', 'volante_calefactado', 'sensores_parking', 'camara_trasera', 'camara_360', 'llave_keyless', 'arranque_boton', 'navegador_gps', 'pantalla_tactil', 'bluetooth', 'apple_carplay', 'android_auto', 'cargador_inalambrico', 'head_up_display', 'cuadro_digital', 'sonido_premium', 'faros_led', 'luces_diurnas_led', 'faros_adaptativos', 'luz_ambiental', 'luces_automaticas', 'luz_larga_automatica', 'cruise_control_adaptativo', 'limitador_velocidad', 'asistente_aparcamiento', 'detector_fatiga', 'reconocimiento_señales', 'frenado_emergencia'],
        created_at: '2024-11-01T10:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        id: '4',
        vin: 'WDBRF61J21F123456',
        matricula: '3456 JKL',
        stock_id: 'MC-004',
        estado: 'disponible',
        destacado: false,
        en_oferta: true,
        marca: 'Mercedes-Benz',
        modelo: 'Clase C',
        version: 'C 200 AMG Line',
        año_fabricacion: 2022,
        año_matriculacion: 2022,
        tipo_motor: 'M264',
        cilindrada: 1991,
        potencia_cv: 204,
        potencia_kw: 150,
        combustible: 'gasolina',
        consumo_mixto: 7.1,
        emisiones_co2: 161,
        etiqueta_dgt: 'C',
        transmision: 'automatico',
        num_marchas: 9,
        traccion: 'Trasera',
        tipo_carroceria: 'Berlina',
        num_puertas: 4,
        num_plazas: 5,
        color_exterior: 'Plata Iridio',
        color_interior: 'Cuero Negro',
        kilometraje: 35000,
        num_propietarios: 1,
        es_nacional: true,
        primera_mano: true,
        precio_compra: 30000,
        gastos_compra: 750,
        coste_reparaciones: 500,
        precio_venta: 38900,
        descuento: 1000,
        margen_bruto: 6650,
        fecha_entrada_stock: '2024-10-25',
        dias_en_stock: 35,
        garantia_meses: 12,
        tipo_garantia: 'Mercedes Certified',
        imagen_principal: 'https://images.unsplash.com/photo-1618843479619-f3d0d81e4d10?w=800',
        imagenes: [],
        created_at: '2024-10-25T10:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        id: '5',
        vin: 'JTDKN3DU5A0123456',
        matricula: '7890 MNO',
        stock_id: 'MC-005',
        estado: 'disponible',
        destacado: false,
        en_oferta: false,
        marca: 'Toyota',
        modelo: 'Corolla',
        version: '1.8 Hybrid Active',
        año_fabricacion: 2023,
        año_matriculacion: 2023,
        tipo_motor: 'Híbrido',
        cilindrada: 1798,
        potencia_cv: 140,
        potencia_kw: 103,
        combustible: 'hibrido',
        consumo_mixto: 4.5,
        emisiones_co2: 102,
        etiqueta_dgt: 'ECO',
        transmision: 'automatico',
        num_marchas: 0,
        traccion: 'Delantera',
        tipo_carroceria: 'Familiar',
        num_puertas: 5,
        num_plazas: 5,
        color_exterior: 'Azul Celestita',
        color_interior: 'Tela Negro',
        kilometraje: 12000,
        num_propietarios: 1,
        es_nacional: true,
        primera_mano: true,
        precio_compra: 20000,
        gastos_compra: 500,
        coste_reparaciones: 0,
        precio_venta: 26900,
        descuento: 0,
        margen_bruto: 6400,
        fecha_entrada_stock: '2024-11-10',
        dias_en_stock: 19,
        garantia_meses: 36,
        tipo_garantia: 'Toyota Relax',
        imagen_principal: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800',
        imagenes: [],
        created_at: '2024-11-10T10:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        id: '6',
        vin: 'VF1RFB00X12345678',
        matricula: '2345 PQR',
        stock_id: 'MC-006',
        estado: 'taller',
        destacado: false,
        en_oferta: false,
        marca: 'Renault',
        modelo: 'Mégane',
        version: 'E-Tech 100% Eléctrico',
        año_fabricacion: 2023,
        año_matriculacion: 2023,
        tipo_motor: 'Eléctrico',
        cilindrada: 0,
        potencia_cv: 220,
        potencia_kw: 160,
        combustible: 'electrico',
        consumo_mixto: 16.1,
        emisiones_co2: 0,
        etiqueta_dgt: '0',
        transmision: 'automatico',
        num_marchas: 1,
        traccion: 'Delantera',
        tipo_carroceria: 'Berlina',
        num_puertas: 5,
        num_plazas: 5,
        color_exterior: 'Azul Rafale',
        color_interior: 'Tela Negro',
        kilometraje: 8000,
        num_propietarios: 1,
        es_nacional: true,
        primera_mano: true,
        precio_compra: 28000,
        gastos_compra: 500,
        coste_reparaciones: 200,
        precio_venta: 34900,
        descuento: 0,
        margen_bruto: 6200,
        fecha_entrada_stock: '2024-11-20',
        dias_en_stock: 9,
        garantia_meses: 24,
        tipo_garantia: 'Renault Ocasión Certificada',
        imagen_principal: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800',
        imagenes: [],
        created_at: '2024-11-20T10:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        id: '7',
        vin: 'WVWZZZ3CZWE789012',
        matricula: '6789 STU',
        stock_id: 'MC-007',
        estado: 'disponible',
        destacado: false,
        en_oferta: false,
        marca: 'Volkswagen',
        modelo: 'Tiguan',
        version: '2.0 TDI R-Line',
        año_fabricacion: 2022,
        año_matriculacion: 2022,
        tipo_motor: 'TDI',
        cilindrada: 1968,
        potencia_cv: 150,
        potencia_kw: 110,
        combustible: 'diesel',
        consumo_mixto: 5.2,
        emisiones_co2: 137,
        etiqueta_dgt: 'C',
        transmision: 'automatico',
        num_marchas: 7,
        traccion: '4Motion',
        tipo_carroceria: 'SUV',
        num_puertas: 5,
        num_plazas: 5,
        color_exterior: 'Negro Profundo',
        color_interior: 'Cuero Negro',
        kilometraje: 38000,
        num_propietarios: 1,
        es_nacional: true,
        primera_mano: true,
        precio_compra: 26000,
        gastos_compra: 600,
        coste_reparaciones: 400,
        precio_venta: 32900,
        descuento: 0,
        margen_bruto: 5900,
        fecha_entrada_stock: '2024-10-05',
        dias_en_stock: 55,
        garantia_meses: 12,
        tipo_garantia: 'Das WeltAuto',
        imagen_principal: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
        imagenes: [],
        created_at: '2024-10-05T10:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        id: '8',
        vin: 'WBAPH5C55BA789012',
        matricula: '0123 VWX',
        stock_id: 'MC-008',
        estado: 'disponible',
        destacado: true,
        en_oferta: true,
        marca: 'BMW',
        modelo: 'X3',
        version: 'xDrive20d M Sport',
        año_fabricacion: 2021,
        año_matriculacion: 2021,
        tipo_motor: 'TwinPower Turbo',
        cilindrada: 1995,
        potencia_cv: 190,
        potencia_kw: 140,
        combustible: 'diesel',
        consumo_mixto: 5.8,
        emisiones_co2: 152,
        etiqueta_dgt: 'C',
        transmision: 'automatico',
        num_marchas: 8,
        traccion: 'xDrive',
        tipo_carroceria: 'SUV',
        num_puertas: 5,
        num_plazas: 5,
        color_exterior: 'Azul Phytonic',
        color_interior: 'Cuero Vernasca Negro',
        kilometraje: 62000,
        num_propietarios: 2,
        es_nacional: true,
        primera_mano: false,
        precio_compra: 28000,
        gastos_compra: 700,
        coste_reparaciones: 1500,
        precio_venta: 38900,
        descuento: 2000,
        margen_bruto: 6700,
        fecha_entrada_stock: '2024-08-15',
        dias_en_stock: 106,
        garantia_meses: 12,
        tipo_garantia: 'BMW Premium Selection',
        imagen_principal: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800',
        imagenes: [],
        created_at: '2024-08-15T10:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        id: '9',
        vin: 'WAUZZZ4G9EN789012',
        matricula: '4567 YZA',
        stock_id: 'MC-009',
        estado: 'reservado',
        destacado: false,
        en_oferta: false,
        marca: 'Audi',
        modelo: 'Q5',
        version: '40 TDI quattro S-Line',
        año_fabricacion: 2023,
        año_matriculacion: 2023,
        tipo_motor: 'TDI',
        cilindrada: 1968,
        potencia_cv: 204,
        potencia_kw: 150,
        combustible: 'diesel',
        consumo_mixto: 5.9,
        emisiones_co2: 155,
        etiqueta_dgt: 'C',
        transmision: 'automatico',
        num_marchas: 7,
        traccion: 'quattro',
        tipo_carroceria: 'SUV',
        num_puertas: 5,
        num_plazas: 5,
        color_exterior: 'Gris Daytona',
        color_interior: 'Cuero Fine Nappa Negro',
        kilometraje: 15000,
        num_propietarios: 1,
        es_nacional: true,
        primera_mano: true,
        precio_compra: 38000,
        gastos_compra: 900,
        coste_reparaciones: 0,
        precio_venta: 49900,
        descuento: 0,
        margen_bruto: 11000,
        fecha_entrada_stock: '2024-11-05',
        dias_en_stock: 24,
        garantia_meses: 24,
        tipo_garantia: 'Audi Approved :plus',
        imagen_principal: 'https://images.unsplash.com/photo-1614162692292-7cb03a31dfc0?w=800',
        imagenes: [],
        created_at: '2024-11-05T10:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        id: '10',
        vin: 'WDBRF61J21F789012',
        matricula: '8901 BCD',
        stock_id: 'MC-010',
        estado: 'disponible',
        destacado: false,
        en_oferta: false,
        marca: 'Mercedes-Benz',
        modelo: 'GLC',
        version: '300 d 4MATIC AMG Line',
        año_fabricacion: 2022,
        año_matriculacion: 2022,
        tipo_motor: 'OM654',
        cilindrada: 1993,
        potencia_cv: 245,
        potencia_kw: 180,
        combustible: 'diesel',
        consumo_mixto: 6.4,
        emisiones_co2: 168,
        etiqueta_dgt: 'C',
        transmision: 'automatico',
        num_marchas: 9,
        traccion: '4MATIC',
        tipo_carroceria: 'SUV',
        num_puertas: 5,
        num_plazas: 5,
        color_exterior: 'Blanco Polar',
        color_interior: 'Cuero ARTICO Negro',
        kilometraje: 42000,
        num_propietarios: 1,
        es_nacional: true,
        primera_mano: true,
        precio_compra: 36000,
        gastos_compra: 850,
        coste_reparaciones: 600,
        precio_venta: 47900,
        descuento: 0,
        margen_bruto: 10450,
        fecha_entrada_stock: '2024-10-18',
        dias_en_stock: 42,
        garantia_meses: 12,
        tipo_garantia: 'Mercedes Certified',
        imagen_principal: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800',
        imagenes: [],
        created_at: '2024-10-18T10:00:00Z',
        updated_at: new Date().toISOString(),
    },
    // Commercial vehicles for backoffice
    {
        id: '11',
        vin: 'ZFA26300006J62212',
        matricula: '5691KNW',
        stock_id: 'MC-011',
        estado: 'disponible',
        destacado: false,
        en_oferta: false,
        marca: 'Fiat',
        modelo: 'Doblo',
        version: '1.6 JTDM Trekking',
        año_fabricacion: 2018,
        año_matriculacion: 2018,
        tipo_motor: 'JTDM',
        cilindrada: 1598,
        potencia_cv: 120,
        potencia_kw: 88,
        combustible: 'diesel',
        consumo_mixto: 5.2,
        emisiones_co2: 137,
        etiqueta_dgt: 'C',
        transmision: 'manual',
        num_marchas: 6,
        traccion: 'Delantera',
        tipo_carroceria: 'Monovolumen',
        num_puertas: 5,
        num_plazas: 5,
        color_exterior: 'Marrón',
        color_interior: 'Negro',
        kilometraje: 107373,
        num_propietarios: 2,
        es_nacional: true,
        primera_mano: false,
        precio_compra: 8500,
        gastos_compra: 300,
        coste_reparaciones: 500,
        precio_venta: 12900,
        descuento: 0,
        margen_bruto: 3600,
        fecha_entrada_stock: '2024-09-16',
        dias_en_stock: 102,
        garantia_meses: 12,
        tipo_garantia: 'Mecánica básica',
        imagen_principal: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        imagenes: [],
        created_at: '2024-09-16T10:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        id: '12',
        vin: 'WF0XXXGCDX1234567',
        matricula: '0002LHX',
        stock_id: 'MC-012',
        estado: 'disponible',
        destacado: true,
        en_oferta: true,
        marca: 'Ford',
        modelo: 'Transit Connect',
        version: '1.5 TDCi Trend',
        año_fabricacion: 2020,
        año_matriculacion: 2020,
        tipo_motor: 'TDCi',
        cilindrada: 1499,
        potencia_cv: 100,
        potencia_kw: 74,
        combustible: 'diesel',
        consumo_mixto: 4.9,
        emisiones_co2: 128,
        etiqueta_dgt: 'C',
        transmision: 'manual',
        num_marchas: 6,
        traccion: 'Delantera',
        tipo_carroceria: 'Monovolumen',
        num_puertas: 5,
        num_plazas: 5,
        color_exterior: 'Blanco',
        color_interior: 'Negro',
        kilometraje: 85000,
        num_propietarios: 1,
        es_nacional: true,
        primera_mano: true,
        precio_compra: 12000,
        gastos_compra: 400,
        coste_reparaciones: 300,
        precio_venta: 16900,
        descuento: 500,
        margen_bruto: 3700,
        fecha_entrada_stock: '2024-11-05',
        dias_en_stock: 52,
        garantia_meses: 12,
        tipo_garantia: 'Mecánica completa',
        imagen_principal: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        imagenes: [],
        created_at: '2024-11-05T10:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        id: '13',
        vin: 'WVWZZZ2KZ5778LBN',
        matricula: '5778LBN',
        stock_id: 'MC-013',
        estado: 'disponible',
        destacado: false,
        en_oferta: false,
        marca: 'Volkswagen',
        modelo: 'Caddy',
        version: '2.0 TDI Kombi',
        año_fabricacion: 2019,
        año_matriculacion: 2019,
        tipo_motor: 'TDI',
        cilindrada: 1968,
        potencia_cv: 102,
        potencia_kw: 75,
        combustible: 'diesel',
        consumo_mixto: 5.5,
        emisiones_co2: 144,
        etiqueta_dgt: 'C',
        transmision: 'manual',
        num_marchas: 5,
        traccion: 'Delantera',
        tipo_carroceria: 'Monovolumen',
        num_puertas: 5,
        num_plazas: 5,
        color_exterior: 'Gris Plata',
        color_interior: 'Negro',
        kilometraje: 95000,
        num_propietarios: 1,
        es_nacional: true,
        primera_mano: true,
        precio_compra: 11000,
        gastos_compra: 350,
        coste_reparaciones: 400,
        precio_venta: 15900,
        descuento: 0,
        margen_bruto: 4150,
        fecha_entrada_stock: '2024-10-20',
        dias_en_stock: 68,
        garantia_meses: 12,
        tipo_garantia: 'Das WeltAuto',
        imagen_principal: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        imagenes: [],
        created_at: '2024-10-20T10:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        id: '14',
        vin: 'VF7GBKFWC6394LZK',
        matricula: '6394LZK',
        stock_id: 'MC-014',
        estado: 'reservado',
        destacado: false,
        en_oferta: false,
        marca: 'Citroën',
        modelo: 'Berlingo',
        version: '1.5 BlueHDi Feel',
        año_fabricacion: 2021,
        año_matriculacion: 2021,
        tipo_motor: 'BlueHDi',
        cilindrada: 1499,
        potencia_cv: 130,
        potencia_kw: 96,
        combustible: 'diesel',
        consumo_mixto: 4.7,
        emisiones_co2: 123,
        etiqueta_dgt: 'C',
        transmision: 'automatico',
        num_marchas: 8,
        traccion: 'Delantera',
        tipo_carroceria: 'Monovolumen',
        num_puertas: 5,
        num_plazas: 7,
        color_exterior: 'Azul',
        color_interior: 'Negro',
        kilometraje: 45000,
        num_propietarios: 1,
        es_nacional: true,
        primera_mano: true,
        precio_compra: 18000,
        gastos_compra: 500,
        coste_reparaciones: 200,
        precio_venta: 23900,
        descuento: 0,
        margen_bruto: 5200,
        fecha_entrada_stock: '2024-11-15',
        dias_en_stock: 42,
        garantia_meses: 24,
        tipo_garantia: 'Citroën Select',
        imagen_principal: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        imagenes: [],
        created_at: '2024-11-15T10:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        id: '15',
        vin: 'ZFA31200007010KNN',
        matricula: '7010KNN',
        stock_id: 'MC-015',
        estado: 'disponible',
        destacado: false,
        en_oferta: true,
        marca: 'Fiat',
        modelo: 'Fiorino',
        version: '1.3 MultiJet Combi',
        año_fabricacion: 2017,
        año_matriculacion: 2017,
        tipo_motor: 'MultiJet',
        cilindrada: 1248,
        potencia_cv: 80,
        potencia_kw: 59,
        combustible: 'diesel',
        consumo_mixto: 4.5,
        emisiones_co2: 119,
        etiqueta_dgt: 'C',
        transmision: 'manual',
        num_marchas: 5,
        traccion: 'Delantera',
        tipo_carroceria: 'Monovolumen',
        num_puertas: 5,
        num_plazas: 5,
        color_exterior: 'Blanco',
        color_interior: 'Gris',
        kilometraje: 125000,
        num_propietarios: 2,
        es_nacional: true,
        primera_mano: false,
        precio_compra: 5500,
        gastos_compra: 250,
        coste_reparaciones: 600,
        precio_venta: 8900,
        descuento: 400,
        margen_bruto: 2150,
        fecha_entrada_stock: '2024-08-10',
        dias_en_stock: 139,
        garantia_meses: 6,
        tipo_garantia: 'Mecánica básica',
        imagen_principal: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        imagenes: [],
        created_at: '2024-08-10T10:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        id: '16',
        vin: 'WV2ZZZ2KZ6317LGY',
        matricula: '6317LGY',
        stock_id: 'MC-016',
        estado: 'taller',
        destacado: false,
        en_oferta: false,
        marca: 'Volkswagen',
        modelo: 'Caddy',
        version: '1.4 TGI Maxi Kombi',
        año_fabricacion: 2020,
        año_matriculacion: 2020,
        tipo_motor: 'TGI',
        cilindrada: 1395,
        potencia_cv: 110,
        potencia_kw: 81,
        combustible: 'gnc',
        consumo_mixto: 4.8,
        emisiones_co2: 117,
        etiqueta_dgt: 'ECO',
        transmision: 'manual',
        num_marchas: 6,
        traccion: 'Delantera',
        tipo_carroceria: 'Monovolumen',
        num_puertas: 5,
        num_plazas: 7,
        color_exterior: 'Negro',
        color_interior: 'Negro',
        kilometraje: 78000,
        num_propietarios: 1,
        es_nacional: true,
        primera_mano: true,
        precio_compra: 15000,
        gastos_compra: 400,
        coste_reparaciones: 800,
        precio_venta: 19900,
        descuento: 0,
        margen_bruto: 3700,
        fecha_entrada_stock: '2024-12-01',
        dias_en_stock: 26,
        garantia_meses: 12,
        tipo_garantia: 'Das WeltAuto',
        imagen_principal: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        imagenes: [],
        created_at: '2024-12-01T10:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        id: '17',
        vin: 'WV1ZZZ7HZ3159LCV',
        matricula: '3159LCV',
        stock_id: 'MC-017',
        estado: 'disponible',
        destacado: true,
        en_oferta: false,
        marca: 'Volkswagen',
        modelo: 'Crafter',
        version: '2.0 TDI L3H2',
        año_fabricacion: 2021,
        año_matriculacion: 2021,
        tipo_motor: 'TDI',
        cilindrada: 1968,
        potencia_cv: 140,
        potencia_kw: 103,
        combustible: 'diesel',
        consumo_mixto: 8.2,
        emisiones_co2: 215,
        etiqueta_dgt: 'C',
        transmision: 'manual',
        num_marchas: 6,
        traccion: 'Delantera',
        tipo_carroceria: 'Monovolumen',
        num_puertas: 4,
        num_plazas: 3,
        color_exterior: 'Blanco',
        color_interior: 'Gris',
        kilometraje: 62000,
        num_propietarios: 1,
        es_nacional: true,
        primera_mano: true,
        precio_compra: 28000,
        gastos_compra: 700,
        coste_reparaciones: 400,
        precio_venta: 35900,
        descuento: 0,
        margen_bruto: 6800,
        fecha_entrada_stock: '2024-11-20',
        dias_en_stock: 37,
        garantia_meses: 24,
        tipo_garantia: 'Das WeltAuto',
        imagen_principal: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        imagenes: [],
        created_at: '2024-11-20T10:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        id: '18',
        vin: 'VF7GBKFW8883KWY',
        matricula: '8883KWY',
        stock_id: 'MC-018',
        estado: 'disponible',
        destacado: false,
        en_oferta: false,
        marca: 'Citroën',
        modelo: 'Berlingo',
        version: '1.6 HDi Multispace',
        año_fabricacion: 2016,
        año_matriculacion: 2016,
        tipo_motor: 'HDi',
        cilindrada: 1560,
        potencia_cv: 92,
        potencia_kw: 68,
        combustible: 'diesel',
        consumo_mixto: 4.9,
        emisiones_co2: 128,
        etiqueta_dgt: 'B',
        transmision: 'manual',
        num_marchas: 5,
        traccion: 'Delantera',
        tipo_carroceria: 'Monovolumen',
        num_puertas: 5,
        num_plazas: 5,
        color_exterior: 'Gris',
        color_interior: 'Negro',
        kilometraje: 145000,
        num_propietarios: 2,
        es_nacional: true,
        primera_mano: false,
        precio_compra: 5000,
        gastos_compra: 200,
        coste_reparaciones: 700,
        precio_venta: 7900,
        descuento: 300,
        margen_bruto: 1700,
        fecha_entrada_stock: '2024-07-15',
        dias_en_stock: 165,
        garantia_meses: 6,
        tipo_garantia: 'Mecánica básica',
        imagen_principal: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        imagenes: [],
        created_at: '2024-07-15T10:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        id: '19',
        vin: 'VF3EUAHK5272LDN',
        matricula: '5272LDN',
        stock_id: 'MC-019',
        estado: 'disponible',
        destacado: false,
        en_oferta: true,
        marca: 'Peugeot',
        modelo: 'Expert',
        version: '2.0 BlueHDi Long',
        año_fabricacion: 2019,
        año_matriculacion: 2019,
        tipo_motor: 'BlueHDi',
        cilindrada: 1997,
        potencia_cv: 150,
        potencia_kw: 110,
        combustible: 'diesel',
        consumo_mixto: 6.3,
        emisiones_co2: 165,
        etiqueta_dgt: 'C',
        transmision: 'manual',
        num_marchas: 6,
        traccion: 'Delantera',
        tipo_carroceria: 'Monovolumen',
        num_puertas: 5,
        num_plazas: 9,
        color_exterior: 'Azul',
        color_interior: 'Negro',
        kilometraje: 89000,
        num_propietarios: 1,
        es_nacional: true,
        primera_mano: true,
        precio_compra: 19000,
        gastos_compra: 500,
        coste_reparaciones: 350,
        precio_venta: 24900,
        descuento: 1000,
        margen_bruto: 4050,
        fecha_entrada_stock: '2024-10-01',
        dias_en_stock: 87,
        garantia_meses: 12,
        tipo_garantia: 'Peugeot Ocasión',
        imagen_principal: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        imagenes: [],
        created_at: '2024-10-01T10:00:00Z',
        updated_at: new Date().toISOString(),
    },
    {
        id: '20',
        vin: 'UU1FSDNNH5109KNL',
        matricula: '5109KNL',
        stock_id: 'MC-020',
        estado: 'disponible',
        destacado: false,
        en_oferta: false,
        marca: 'Dacia',
        modelo: 'Dokker',
        version: '1.5 dCi Ambiance',
        año_fabricacion: 2018,
        año_matriculacion: 2018,
        tipo_motor: 'dCi',
        cilindrada: 1461,
        potencia_cv: 90,
        potencia_kw: 66,
        combustible: 'diesel',
        consumo_mixto: 4.6,
        emisiones_co2: 120,
        etiqueta_dgt: 'C',
        transmision: 'manual',
        num_marchas: 5,
        traccion: 'Delantera',
        tipo_carroceria: 'Monovolumen',
        num_puertas: 5,
        num_plazas: 5,
        color_exterior: 'Blanco Glaciar',
        color_interior: 'Negro',
        kilometraje: 112000,
        num_propietarios: 1,
        es_nacional: true,
        primera_mano: true,
        precio_compra: 6000,
        gastos_compra: 250,
        coste_reparaciones: 400,
        precio_venta: 9900,
        descuento: 0,
        margen_bruto: 3250,
        fecha_entrada_stock: '2024-09-25',
        dias_en_stock: 93,
        garantia_meses: 12,
        tipo_garantia: 'Mecánica básica',
        imagen_principal: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        imagenes: [],
        created_at: '2024-09-25T10:00:00Z',
        updated_at: new Date().toISOString(),
    },
]

export const mockClients: Client[] = [
    {
        id: '1',
        tipo_cliente: 'particular',
        nombre: 'Carlos',
        apellidos: 'García Fernández',
        razon_social: null,
        nif_nie: '12345678A',
        cif: null,
        email: 'carlos.garcia@email.com',
        telefono: '+34 612 345 678',
        direccion: 'Calle Mayor 123',
        cp: '28850',
        municipio: 'Torrejón de Ardoz',
        provincia: 'Madrid',
        preferencias_comunicacion: ['whatsapp', 'email'],
        acepta_marketing: true,
        origen_lead: 'Web',
        consentimiento_rgpd: true,
        fecha_registro: '2024-11-28T10:30:00Z',
        created_at: '2024-11-28T10:30:00Z',
    },
    {
        id: '2',
        tipo_cliente: 'particular',
        nombre: 'Ana',
        apellidos: 'Martínez López',
        razon_social: null,
        nif_nie: '87654321B',
        cif: null,
        email: 'ana.martinez@email.com',
        telefono: '+34 623 456 789',
        direccion: null,
        cp: null,
        municipio: 'Madrid',
        provincia: 'Madrid',
        preferencias_comunicacion: ['llamada'],
        acepta_marketing: false,
        origen_lead: 'Web',
        consentimiento_rgpd: true,
        fecha_registro: '2024-11-25T14:20:00Z',
        created_at: '2024-11-25T14:20:00Z',
    },
    {
        id: '3',
        tipo_cliente: 'empresa',
        nombre: 'Roberto',
        apellidos: 'Sánchez',
        razon_social: 'Transportes Rápido SL',
        nif_nie: null,
        cif: 'B12345678',
        email: 'roberto@transportesrapido.es',
        telefono: '+34 634 567 890',
        direccion: 'Polígono Industrial Norte, Nave 45',
        cp: '28850',
        municipio: 'Torrejón de Ardoz',
        provincia: 'Madrid',
        preferencias_comunicacion: ['email'],
        acepta_marketing: true,
        origen_lead: 'Visita',
        consentimiento_rgpd: true,
        fecha_registro: '2024-11-20T09:00:00Z',
        created_at: '2024-11-20T09:00:00Z',
    },
]

// Mock Leads
export const mockLeads: Lead[] = [
    {
        id: '1',
        cliente_id: '1',
        vehiculo_id: '3',
        estado: 'nuevo',
        prioridad: 'alta',
        probabilidad: 70,
        tipo_interes: 'Compra',
        presupuesto_cliente: 45000,
        forma_pago: 'Financiación',
        asignado_a: '2',
        transcript_chatbot: [
            { role: 'assistant', content: '¡Hola! Bienvenido a MidCar. ¿En qué puedo ayudarte hoy?', timestamp: '2024-11-28T10:30:00Z' },
            { role: 'user', content: 'Hola, estoy buscando un BMW Serie 3', timestamp: '2024-11-28T10:30:15Z' },
            { role: 'assistant', content: 'Excelente elección. Tenemos un BMW 320d M Sport de 2023 con solo 18.000 km a un precio muy competitivo de 42.900€. ¿Te gustaría más detalles?', timestamp: '2024-11-28T10:30:20Z' },
            { role: 'user', content: 'Sí, me interesa. ¿Tiene financiación?', timestamp: '2024-11-28T10:30:45Z' },
            { role: 'assistant', content: 'Por supuesto. Ofrecemos financiación hasta 84 meses con cuotas desde 449€/mes. ¿Puedo tomar tus datos para que un asesor te contacte?', timestamp: '2024-11-28T10:30:50Z' },
            { role: 'user', content: 'Vale, soy Carlos García, mi teléfono es 612345678', timestamp: '2024-11-28T10:31:20Z' },
        ],
        sentimiento_ia: 'positivo',
        fecha_creacion: '2024-11-28T10:31:30Z',
        fecha_cierre: null,
        ultima_interaccion: '2024-11-28T10:31:30Z',
        proxima_accion: 'Llamar al cliente',
        fecha_proxima_accion: new Date().toISOString(),
        motivo_perdida: null,
        notas: 'Cliente muy interesado, preguntó específicamente por financiación.',
        cliente: mockClients[0],
        vehiculo: mockVehicles[2],
        vendedor: mockUsers[1],
    },
    {
        id: '2',
        cliente_id: '2',
        vehiculo_id: '1',
        estado: 'contactado',
        prioridad: 'media',
        probabilidad: 50,
        tipo_interes: 'Compra',
        presupuesto_cliente: 25000,
        forma_pago: 'Contado',
        asignado_a: '3',
        transcript_chatbot: [
            { role: 'assistant', content: '¡Hola! Bienvenido a MidCar. ¿En qué puedo ayudarte hoy?', timestamp: '2024-11-25T14:20:00Z' },
            { role: 'user', content: 'Busco un coche familiar, diesel, máximo 25.000€', timestamp: '2024-11-25T14:20:30Z' },
            { role: 'assistant', content: 'Tengo varias opciones para ti. El Volkswagen Golf 2.0 TDI Sport de 2022 con 45.000 km está en oferta a 24.400€. Es muy espacioso y económico.', timestamp: '2024-11-25T14:20:35Z' },
        ],
        sentimiento_ia: 'neutral',
        fecha_creacion: '2024-11-25T14:21:00Z',
        fecha_cierre: null,
        ultima_interaccion: '2024-11-26T11:00:00Z',
        proxima_accion: 'Enviar propuesta formal',
        fecha_proxima_accion: new Date(Date.now() + 86400000).toISOString(),
        motivo_perdida: null,
        notas: 'Contactada por teléfono, quedó en visitar el concesionario el sábado.',
        cliente: mockClients[1],
        vehiculo: mockVehicles[0],
        vendedor: mockUsers[2],
    },
    {
        id: '3',
        cliente_id: '3',
        vehiculo_id: '4',
        estado: 'visita_agendada',
        prioridad: 'urgente',
        probabilidad: 85,
        tipo_interes: 'Compra',
        presupuesto_cliente: 40000,
        forma_pago: 'Renting',
        asignado_a: '2',
        transcript_chatbot: [],
        sentimiento_ia: 'positivo',
        fecha_creacion: '2024-11-20T09:00:00Z',
        fecha_cierre: null,
        ultima_interaccion: '2024-11-27T16:00:00Z',
        proxima_accion: 'Prueba de conducción programada',
        fecha_proxima_accion: new Date(Date.now() + 172800000).toISOString(),
        motivo_perdida: null,
        notas: 'Empresa busca renovar flota. Interesados en 2-3 vehículos.',
        cliente: mockClients[2],
        vehiculo: mockVehicles[3],
        vendedor: mockUsers[1],
    },
    {
        id: '4',
        cliente_id: '1',
        vehiculo_id: '5',
        estado: 'vendido',
        prioridad: 'alta',
        probabilidad: 100,
        tipo_interes: 'Compra',
        presupuesto_cliente: 28000,
        forma_pago: 'Contado',
        asignado_a: '2',
        transcript_chatbot: [],
        sentimiento_ia: 'positivo',
        fecha_creacion: '2024-11-01T10:00:00Z',
        fecha_cierre: '2024-11-15T12:00:00Z',
        ultima_interaccion: '2024-11-15T12:00:00Z',
        proxima_accion: null,
        fecha_proxima_accion: null,
        motivo_perdida: null,
        notas: 'Venta cerrada. Cliente recogió el vehículo el día 20.',
        cliente: mockClients[0],
        vehiculo: mockVehicles[4],
        vendedor: mockUsers[1],
    },
    {
        id: '5',
        cliente_id: '2',
        vehiculo_id: '2',
        estado: 'perdido',
        prioridad: 'baja',
        probabilidad: 0,
        tipo_interes: 'Compra',
        presupuesto_cliente: 30000,
        forma_pago: 'Financiación',
        asignado_a: '3',
        transcript_chatbot: [],
        sentimiento_ia: 'negativo',
        fecha_creacion: '2024-10-15T14:00:00Z',
        fecha_cierre: '2024-10-28T10:00:00Z',
        ultima_interaccion: '2024-10-28T10:00:00Z',
        proxima_accion: null,
        fecha_proxima_accion: null,
        motivo_perdida: 'Compró en otra marca',
        notas: 'Cliente decidió comprar un Volvo en otro concesionario.',
        cliente: mockClients[1],
        vehiculo: mockVehicles[1],
        vendedor: mockUsers[2],
    },
]

// Dashboard KPIs
export const mockKPIs: KPI[] = [
    {
        label: 'Leads Hoy',
        value: 5,
        previousValue: 3,
        changePercent: 66.7,
        trend: 'up',
        format: 'number',
    },
    {
        label: 'Leads Este Mes',
        value: 47,
        previousValue: 42,
        changePercent: 11.9,
        trend: 'up',
        format: 'number',
    },
    {
        label: 'Tasa de Conversión',
        value: 23.4,
        previousValue: 21.8,
        changePercent: 7.3,
        trend: 'up',
        format: 'percentage',
    },
    {
        label: 'Vehículos Vendidos',
        value: 11,
        previousValue: 9,
        changePercent: 22.2,
        trend: 'up',
        format: 'number',
    },
    {
        label: 'Stock Actual',
        value: 82,
        previousValue: 85,
        changePercent: -3.5,
        trend: 'down',
        format: 'number',
    },
]

// Chart data for leads over time
export const mockLeadsChartData = [
    { date: '01/11', leads: 3 },
    { date: '02/11', leads: 5 },
    { date: '03/11', leads: 2 },
    { date: '04/11', leads: 4 },
    { date: '05/11', leads: 6 },
    { date: '06/11', leads: 3 },
    { date: '07/11', leads: 4 },
    { date: '08/11', leads: 7 },
    { date: '09/11', leads: 5 },
    { date: '10/11', leads: 3 },
    { date: '11/11', leads: 6 },
    { date: '12/11', leads: 4 },
    { date: '13/11', leads: 5 },
    { date: '14/11', leads: 8 },
    { date: '15/11', leads: 6 },
    { date: '16/11', leads: 4 },
    { date: '17/11', leads: 3 },
    { date: '18/11', leads: 5 },
    { date: '19/11', leads: 7 },
    { date: '20/11', leads: 4 },
    { date: '21/11', leads: 6 },
    { date: '22/11', leads: 5 },
    { date: '23/11', leads: 3 },
    { date: '24/11', leads: 4 },
    { date: '25/11', leads: 6 },
    { date: '26/11', leads: 8 },
    { date: '27/11', leads: 5 },
    { date: '28/11', leads: 7 },
    { date: '29/11', leads: 4 },
    { date: '30/11', leads: 5 },
]

// Chart data for sales
export const mockSalesChartData = [
    { date: '01/11', ventas: 2, ingresos: 48000 },
    { date: '05/11', ventas: 1, ingresos: 28000 },
    { date: '08/11', ventas: 2, ingresos: 52000 },
    { date: '12/11', ventas: 1, ingresos: 24000 },
    { date: '15/11', ventas: 3, ingresos: 89000 },
    { date: '19/11', ventas: 1, ingresos: 32000 },
    { date: '22/11', ventas: 2, ingresos: 61000 },
    { date: '26/11', ventas: 1, ingresos: 27000 },
    { date: '29/11', ventas: 2, ingresos: 54000 },
]

// Chatbot stats
export const mockChatbotStats = {
    conversacionesHoy: 12,
    conversacionesMes: 156,
    leadsGenerados: 47,
    tasaConversion: 30.1,
    tiempoPromedioMinutos: 4.2,
    satisfaccion: 4.5,
}

// Funnel data
export const mockFunnelData = [
    { etapa: 'Visitantes Web', valor: 1250, porcentaje: 100 },
    { etapa: 'Visitan Stock', valor: 312, porcentaje: 25.0 },
    { etapa: 'Consultan Vehículos', valor: 187, porcentaje: 15.0 },
    { etapa: 'Generan Lead', valor: 47, porcentaje: 3.8 },
    { etapa: 'Agendan Cita', valor: 18, porcentaje: 1.4 },
]

// Mock Contacts
import type { Contact } from '@/types'

export const mockContacts: Contact[] = [
    {
        id: 'c1',
        telefono: '+34 612 345 678',
        email: 'carlos.garcia@email.com',
        nombre: 'Carlos',
        apellidos: 'García Fernández',
        dni_cif: '12345678A',
        direccion: 'Calle Mayor 123',
        codigo_postal: '28850',
        municipio: 'Torrejón de Ardoz',
        provincia: 'Madrid',
        origen: 'whatsapp',
        estado: 'pendiente',
        vehiculos_interes: ['1', '3'],
        preferencias_comunicacion: ['whatsapp', 'email'],
        acepta_marketing: true,
        consentimiento_rgpd: true,
        notas: 'Interesado en BMW Serie 3 o Golf. Presupuesto máximo 45.000€',
        fecha_registro: '2024-12-18T10:30:00Z',
        ultima_interaccion: '2024-12-18T10:30:00Z',
        created_at: '2024-12-18T10:30:00Z',
        updated_at: '2024-12-18T10:30:00Z',
        progreso: 25,
        fecha_ultimo_contacto: '2024-12-18T10:30:00Z',
        categoria: 'vehiculo',
        asunto: 'Información vehículo',
        comercial_asignado: '2',
        tipo_pago: 'financiacion',
        es_nuevo_cliente: true,
    },
    {
        id: 'c2',
        telefono: '+34 623 456 789',
        email: 'ana.martinez@email.com',
        nombre: 'Ana',
        apellidos: 'Martínez López',
        origen: 'web',
        estado: 'postventa',
        vehiculos_interes: ['1'],
        preferencias_comunicacion: ['llamada'],
        acepta_marketing: false,
        consentimiento_rgpd: true,
        notas: 'Busca coche familiar, diesel, máximo 25.000€',
        fecha_registro: '2024-12-15T14:20:00Z',
        ultima_interaccion: '2024-12-17T11:00:00Z',
        created_at: '2024-12-15T14:20:00Z',
        updated_at: '2024-12-17T11:00:00Z',
        progreso: 100,
        fecha_ultimo_contacto: '2024-12-17T11:00:00Z',
        categoria: 'postventa',
        asunto: 'Garantía',
        comercial_asignado: '3',
        tipo_pago: 'contado',
        es_nuevo_cliente: false,
    },
    {
        id: 'c3',
        telefono: '+34 634 567 890',
        email: 'roberto@transportesrapido.es',
        nombre: 'Roberto',
        apellidos: 'Sánchez',
        dni_cif: 'B12345678',
        direccion: 'Polígono Industrial Norte, Nave 45',
        codigo_postal: '28850',
        municipio: 'Torrejón de Ardoz',
        provincia: 'Madrid',
        datos_facturacion: {
            tipo_cliente: 'empresa',
            tipo_documento: 'cif',
            razon_social: 'Transportes Rápido SL',
            cif_nif: 'B12345678',
            direccion_fiscal: 'Polígono Industrial Norte, Nave 45',
            codigo_postal: '28850',
            municipio: 'Torrejón de Ardoz',
            provincia: 'Madrid',
            comunidad: 'madrid',
            pais: 'España',
        },
        origen: 'presencial',
        estado: 'tramite',
        vehiculos_interes: ['11', '12', '17'],
        preferencias_comunicacion: ['email'],
        acepta_marketing: true,
        consentimiento_rgpd: true,
        notas: 'Empresa busca renovar flota. Interesados en 2-3 vehículos comerciales.',
        fecha_registro: '2024-12-10T09:00:00Z',
        ultima_interaccion: '2024-12-18T16:00:00Z',
        created_at: '2024-12-10T09:00:00Z',
        updated_at: '2024-12-18T16:00:00Z',
        progreso: 50,
        fecha_ultimo_contacto: '2024-12-18T16:00:00Z',
        categoria: 'vehiculo',
        asunto: 'Información vehículo',
        comercial_asignado: '2',
        tipo_pago: 'renting',
        precio: 72700,
        reserva: 5000,
        es_nuevo_cliente: false,
    },
    {
        id: 'c4',
        telefono: '+34 645 678 901',
        email: 'luis.perez@gmail.com',
        nombre: 'Luis',
        apellidos: 'Pérez Ruiz',
        origen: 'coches_net',
        estado: 'pendiente',
        vehiculos_interes: ['2'],
        preferencias_comunicacion: ['whatsapp'],
        acepta_marketing: true,
        consentimiento_rgpd: true,
        fecha_registro: '2024-12-18T15:45:00Z',
        created_at: '2024-12-18T15:45:00Z',
        updated_at: '2024-12-18T15:45:00Z',
        progreso: 0,
        fecha_ultimo_contacto: '2024-12-18T15:45:00Z',
        categoria: 'vehiculo',
        asunto: 'Consulta de precio',
        comercial_asignado: '3',
        es_nuevo_cliente: true,
    },
    {
        id: 'c5',
        telefono: '+34 656 789 012',
        email: 'maria.gomez@outlook.es',
        nombre: 'María',
        apellidos: 'Gómez Ruiz',
        origen: 'wallapop',
        estado: 'comunicado',
        vehiculos_interes: ['5', '6'],
        preferencias_comunicacion: ['llamada', 'email'],
        acepta_marketing: false,
        consentimiento_rgpd: true,
        notas: 'Preguntó por Toyota Corolla híbrido. Quiere etiqueta ECO.',
        fecha_registro: '2024-12-16T11:30:00Z',
        ultima_interaccion: '2024-12-17T18:00:00Z',
        created_at: '2024-12-16T11:30:00Z',
        updated_at: '2024-12-17T18:00:00Z',
        progreso: 35,
        fecha_ultimo_contacto: '2024-12-17T18:00:00Z',
        categoria: 'vehiculo',
        asunto: 'Información vehículo',
        comercial_asignado: '2',
        tipo_pago: 'contado',
        es_nuevo_cliente: true,
    },
    {
        id: 'c6',
        telefono: '+34 667 890 123',
        email: 'pedro.fernandez@empresa.com',
        nombre: 'Pedro',
        apellidos: 'Fernández García',
        origen: 'telefono',
        estado: 'cerrado',
        vehiculos_interes: [],
        preferencias_comunicacion: ['llamada'],
        acepta_marketing: false,
        consentimiento_rgpd: true,
        notas: 'Llamó preguntando precios generales. No mostró interés específico.',
        fecha_registro: '2024-12-01T10:00:00Z',
        ultima_interaccion: '2024-12-01T10:00:00Z',
        created_at: '2024-12-01T10:00:00Z',
        updated_at: '2024-12-01T10:00:00Z',
        progreso: 100,
        fecha_ultimo_contacto: '2024-12-01T10:00:00Z',
        categoria: 'otro',
        asunto: 'Consulta de precio',
        comercial_asignado: '3',
        es_nuevo_cliente: true,
    },
    {
        id: 'c7',
        telefono: '+34 678 901 234',
        email: 'laura.jimenez@yahoo.es',
        nombre: 'Laura',
        apellidos: 'Jiménez Torres',
        dni_cif: '87654321B',
        origen: 'referido',
        estado: 'reservado',
        vehiculos_interes: ['8', '9'],
        preferencias_comunicacion: ['whatsapp', 'email'],
        acepta_marketing: true,
        consentimiento_rgpd: true,
        notas: 'Referida por Carlos García (c1). Busca SUV premium.',
        fecha_registro: '2024-12-18T09:00:00Z',
        created_at: '2024-12-18T09:00:00Z',
        updated_at: '2024-12-18T09:00:00Z',
        progreso: 75,
        fecha_ultimo_contacto: '2024-12-20T14:30:00Z',
        categoria: 'vehiculo',
        asunto: 'Solicitud de cita',
        comercial_asignado: '2',
        tipo_pago: 'financiacion',
        precio: 38900,
        reserva: 2000,
        es_nuevo_cliente: true,
    },
    {
        id: 'c8',
        telefono: '+34 689 012 345',
        email: 'alejandro.martin@gmail.com',
        nombre: 'Alejandro',
        apellidos: 'Martín Ruiz',
        origen: 'web',
        estado: 'pendiente',
        vehiculos_interes: ['11'],
        preferencias_comunicacion: ['email'],
        acepta_marketing: true,
        consentimiento_rgpd: true,
        notas: 'Le ofrezco otro modelo por email',
        fecha_registro: '2024-12-20T08:15:00Z',
        created_at: '2024-12-20T08:15:00Z',
        updated_at: '2024-12-20T08:15:00Z',
        progreso: 10,
        fecha_ultimo_contacto: '2024-12-20T08:15:00Z',
        categoria: 'vehiculo',
        asunto: 'Información vehículo',
        comercial_asignado: '3',
        es_nuevo_cliente: true,
    },
    {
        id: 'c9',
        telefono: '+34 690 123 456',
        email: 'isabel.gonzalez@hotmail.com',
        nombre: 'Isabel',
        apellidos: 'González Díaz',
        origen: 'coches_net',
        estado: 'postventa',
        vehiculos_interes: ['4'],
        preferencias_comunicacion: ['llamada', 'whatsapp'],
        acepta_marketing: true,
        consentimiento_rgpd: true,
        notas: 'Compró Mercedes Clase C. Satisfecha con la compra.',
        fecha_registro: '2024-11-15T10:00:00Z',
        ultima_interaccion: '2024-12-19T11:00:00Z',
        created_at: '2024-11-15T10:00:00Z',
        updated_at: '2024-12-19T11:00:00Z',
        progreso: 100,
        fecha_ultimo_contacto: '2024-12-19T11:00:00Z',
        categoria: 'postventa',
        asunto: 'Garantía',
        comercial_asignado: '2',
        tipo_pago: 'financiacion',
        es_nuevo_cliente: false,
    },
    {
        id: 'c10',
        telefono: '+34 601 234 567',
        email: 'francisco.lopez@empresa.es',
        nombre: 'Francisco',
        apellidos: 'López García',
        origen: 'presencial',
        estado: 'tramite',
        vehiculos_interes: ['12', '13'],
        preferencias_comunicacion: ['email'],
        acepta_marketing: false,
        consentimiento_rgpd: true,
        notas: 'Empresario, busca furgoneta para reparto.',
        fecha_registro: '2024-12-19T16:30:00Z',
        created_at: '2024-12-19T16:30:00Z',
        updated_at: '2024-12-19T16:30:00Z',
        progreso: 50,
        fecha_ultimo_contacto: '2024-12-19T16:30:00Z',
        categoria: 'vehiculo',
        asunto: 'Información vehículo',
        comercial_asignado: '2',
        tipo_pago: 'renting',
        es_nuevo_cliente: true,
    },
    {
        id: 'c11',
        telefono: '+34 612 345 890',
        email: 'carmen.rodriguez@gmail.com',
        nombre: 'Carmen',
        apellidos: 'Rodríguez Muñoz',
        origen: 'wallapop',
        estado: 'busqueda',
        vehiculos_interes: [],
        preferencias_comunicacion: ['whatsapp'],
        acepta_marketing: true,
        consentimiento_rgpd: true,
        notas: 'Busca coche pequeño para ciudad. Presupuesto bajo.',
        fecha_registro: '2024-12-18T12:00:00Z',
        created_at: '2024-12-18T12:00:00Z',
        updated_at: '2024-12-18T12:00:00Z',
        progreso: 15,
        fecha_ultimo_contacto: '2024-12-18T12:00:00Z',
        categoria: 'vehiculo',
        asunto: 'Consulta de precio',
        comercial_asignado: '3',
        es_nuevo_cliente: true,
    },
    {
        id: 'c12',
        telefono: '+34 623 456 012',
        email: 'javier.sanchez@outlook.es',
        nombre: 'Javier',
        apellidos: 'Sánchez Moreno',
        origen: 'telefono',
        estado: 'cerrado',
        vehiculos_interes: ['7'],
        preferencias_comunicacion: ['llamada'],
        acepta_marketing: false,
        consentimiento_rgpd: true,
        notas: 'Compró Volkswagen Tiguan. Entrega realizada.',
        fecha_registro: '2024-11-01T09:00:00Z',
        ultima_interaccion: '2024-11-20T14:00:00Z',
        created_at: '2024-11-01T09:00:00Z',
        updated_at: '2024-11-20T14:00:00Z',
        progreso: 100,
        fecha_ultimo_contacto: '2024-11-20T14:00:00Z',
        categoria: 'vehiculo',
        asunto: 'Información vehículo',
        comercial_asignado: '2',
        tipo_pago: 'contado',
        es_nuevo_cliente: false,
    },
    {
        id: 'c13',
        telefono: '+34 634 567 123',
        email: 'elena.diaz@yahoo.es',
        nombre: 'Elena',
        apellidos: 'Díaz Romero',
        origen: 'web',
        estado: 'pendiente',
        vehiculos_interes: ['5'],
        preferencias_comunicacion: ['email', 'whatsapp'],
        acepta_marketing: true,
        consentimiento_rgpd: true,
        notas: 'Interesada en Toyota Corolla híbrido. Primera consulta.',
        fecha_registro: '2024-12-21T10:00:00Z',
        created_at: '2024-12-21T10:00:00Z',
        updated_at: '2024-12-21T10:00:00Z',
        progreso: 0,
        fecha_ultimo_contacto: '2024-12-21T10:00:00Z',
        categoria: 'vehiculo',
        asunto: 'Información vehículo',
        comercial_asignado: '3',
        es_nuevo_cliente: true,
    },
    {
        id: 'c14',
        telefono: '+34 645 678 234',
        email: 'miguel.herrera@empresa.com',
        nombre: 'Miguel',
        apellidos: 'Herrera Navarro',
        origen: 'referido',
        estado: 'comunicado',
        vehiculos_interes: ['14', '19'],
        preferencias_comunicacion: ['llamada'],
        acepta_marketing: true,
        consentimiento_rgpd: true,
        notas: 'Referido por cliente anterior. Busca furgoneta 7 plazas.',
        fecha_registro: '2024-12-19T09:30:00Z',
        ultima_interaccion: '2024-12-20T11:00:00Z',
        created_at: '2024-12-19T09:30:00Z',
        updated_at: '2024-12-20T11:00:00Z',
        progreso: 40,
        fecha_ultimo_contacto: '2024-12-20T11:00:00Z',
        categoria: 'vehiculo',
        asunto: 'Solicitud de cita',
        comercial_asignado: '2',
        tipo_pago: 'financiacion',
        es_nuevo_cliente: true,
    },
    {
        id: 'c15',
        telefono: '+34 656 789 345',
        email: 'patricia.ruiz@gmail.com',
        nombre: 'Patricia',
        apellidos: 'Ruiz Serrano',
        origen: 'autocasion',
        estado: 'postventa',
        vehiculos_interes: ['2'],
        preferencias_comunicacion: ['email'],
        acepta_marketing: false,
        consentimiento_rgpd: true,
        notas: 'Entrega realizada. Revisión de garantía pendiente.',
        fecha_registro: '2024-10-15T14:00:00Z',
        ultima_interaccion: '2024-12-15T10:00:00Z',
        created_at: '2024-10-15T14:00:00Z',
        updated_at: '2024-12-15T10:00:00Z',
        progreso: 100,
        fecha_ultimo_contacto: '2024-12-15T10:00:00Z',
        categoria: 'postventa',
        asunto: 'Garantía',
        comercial_asignado: '3',
        tipo_pago: 'contado',
        es_nuevo_cliente: false,
    },
    {
        id: 'c16',
        telefono: '+34 667 890 456',
        email: 'antonio.ortiz@hotmail.com',
        nombre: 'Antonio',
        apellidos: 'Ortiz Blanco',
        origen: 'facebook',
        estado: 'busqueda',
        vehiculos_interes: [],
        preferencias_comunicacion: ['whatsapp', 'email'],
        acepta_marketing: true,
        consentimiento_rgpd: true,
        notas: 'Busca SUV grande. Sin preferencia de marca.',
        fecha_registro: '2024-12-20T16:00:00Z',
        created_at: '2024-12-20T16:00:00Z',
        updated_at: '2024-12-20T16:00:00Z',
        progreso: 20,
        fecha_ultimo_contacto: '2024-12-20T16:00:00Z',
        categoria: 'vehiculo',
        asunto: 'Consulta de precio',
        comercial_asignado: '2',
        es_nuevo_cliente: true,
    },
    {
        id: 'c17',
        telefono: '+34 678 901 567',
        email: 'rosa.morales@yahoo.es',
        nombre: 'Rosa',
        apellidos: 'Morales Castro',
        origen: 'instagram',
        estado: 'pendiente',
        vehiculos_interes: ['6'],
        preferencias_comunicacion: ['email'],
        acepta_marketing: true,
        consentimiento_rgpd: true,
        notas: 'Interesada en coche eléctrico. Pregunta por ayudas.',
        fecha_registro: '2024-12-21T08:00:00Z',
        created_at: '2024-12-21T08:00:00Z',
        updated_at: '2024-12-21T08:00:00Z',
        progreso: 5,
        fecha_ultimo_contacto: '2024-12-21T08:00:00Z',
        categoria: 'financiacion',
        asunto: 'Consulta financiación',
        comercial_asignado: '3',
        es_nuevo_cliente: true,
    },
    {
        id: 'c18',
        telefono: '+34 689 012 678',
        email: 'daniel.santos@gmail.com',
        nombre: 'Daniel',
        apellidos: 'Santos Iglesias',
        origen: 'presencial',
        estado: 'reservado',
        vehiculos_interes: ['3'],
        preferencias_comunicacion: ['llamada', 'whatsapp'],
        acepta_marketing: true,
        consentimiento_rgpd: true,
        notas: 'Ha dejado señal para BMW Serie 3. Pendiente financiación.',
        fecha_registro: '2024-12-15T11:00:00Z',
        ultima_interaccion: '2024-12-20T16:00:00Z',
        created_at: '2024-12-15T11:00:00Z',
        updated_at: '2024-12-20T16:00:00Z',
        progreso: 80,
        fecha_ultimo_contacto: '2024-12-20T16:00:00Z',
        categoria: 'vehiculo',
        asunto: 'Información vehículo',
        comercial_asignado: '2',
        tipo_pago: 'financiacion',
        precio: 42900,
        reserva: 3000,
        es_nuevo_cliente: true,
    },
    {
        id: 'c19',
        telefono: '+34 690 123 789',
        email: 'lucia.mendez@empresa.es',
        nombre: 'Lucía',
        apellidos: 'Méndez Vargas',
        dni_cif: 'B98765432',
        origen: 'telefono',
        estado: 'tramite',
        vehiculos_interes: ['17', '19'],
        preferencias_comunicacion: ['email'],
        acepta_marketing: false,
        consentimiento_rgpd: true,
        notas: 'Empresa de mensajería. Necesita 2 furgonetas grandes.',
        datos_facturacion: {
            tipo_cliente: 'empresa',
            tipo_documento: 'cif',
            razon_social: 'Mensajería Express SL',
            cif_nif: 'B98765432',
            direccion_fiscal: 'Av. de la Constitución 45',
            codigo_postal: '28004',
            municipio: 'Madrid',
            provincia: 'Madrid',
            comunidad: 'madrid',
            pais: 'España',
        },
        fecha_registro: '2024-12-18T14:00:00Z',
        ultima_interaccion: '2024-12-21T09:00:00Z',
        created_at: '2024-12-18T14:00:00Z',
        updated_at: '2024-12-21T09:00:00Z',
        progreso: 60,
        fecha_ultimo_contacto: '2024-12-21T09:00:00Z',
        categoria: 'vehiculo',
        asunto: 'Información vehículo',
        comercial_asignado: '2',
        tipo_pago: 'renting',
        precio: 60800,
        reserva: 0,
        es_nuevo_cliente: true,
    },
    {
        id: 'c20',
        telefono: '+34 601 234 890',
        email: 'sergio.castro@outlook.es',
        nombre: 'Sergio',
        apellidos: 'Castro Vega',
        origen: 'wallapop',
        estado: 'cerrado',
        vehiculos_interes: ['15'],
        preferencias_comunicacion: ['whatsapp'],
        acepta_marketing: true,
        consentimiento_rgpd: true,
        notas: 'Perdido por precio. Encontró algo más barato.',
        fecha_registro: '2024-12-10T10:00:00Z',
        ultima_interaccion: '2024-12-15T12:00:00Z',
        created_at: '2024-12-10T10:00:00Z',
        updated_at: '2024-12-15T12:00:00Z',
        progreso: 100,
        fecha_ultimo_contacto: '2024-12-15T12:00:00Z',
        categoria: 'vehiculo',
        asunto: 'Consulta de precio',
        comercial_asignado: '3',
        tipo_pago: 'contado',
        es_nuevo_cliente: true,
    },
    {
        id: 'c21',
        telefono: '+34 612 345 901',
        email: 'beatriz.romero@gmail.com',
        nombre: 'Beatriz',
        apellidos: 'Romero Prieto',
        origen: 'coches_net',
        estado: 'pendiente',
        vehiculos_interes: ['13', '14'],
        preferencias_comunicacion: ['llamada', 'email'],
        acepta_marketing: true,
        consentimiento_rgpd: true,
        notas: 'Busca monovolumen familiar. 7 plazas imprescindible.',
        fecha_registro: '2024-12-21T11:30:00Z',
        created_at: '2024-12-21T11:30:00Z',
        updated_at: '2024-12-21T11:30:00Z',
        progreso: 0,
        fecha_ultimo_contacto: '2024-12-21T11:30:00Z',
        categoria: 'vehiculo',
        asunto: 'Información vehículo',
        comercial_asignado: '2',
        es_nuevo_cliente: true,
    },
]


