"use client"

import { useState, Suspense } from "react"
import { Button } from "@/components/ui/button"
import { ArrowLeft } from "lucide-react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { VehicleForm, VehicleFormData } from "@/components/inventory/VehicleForm"
import { useToast } from "@/components/ui/toast"
import { createVehicle, generateStockId } from "@/lib/supabase-service"
import { uploadVehicleImage } from "@/lib/vehicle-image-service"
import { useAuth } from "@/lib/auth-context"
import { invalidateDataCache } from "@/hooks/useFilteredData"
import type { Vehicle } from "@/types"

function NuevoVehiculoContent() {
    const router = useRouter()
    const { addToast } = useToast()
    const { user, profile } = useAuth()
    const [isSaving, setIsSaving] = useState(false)


    // Helper function to convert File to base64 (for documents - no compression)
    const fileToBase64 = (file: File): Promise<string> => {
        return new Promise((resolve, reject) => {
            const reader = new FileReader()
            reader.onload = () => resolve(reader.result as string)
            reader.onerror = reject
            reader.readAsDataURL(file)
        })
    }

    // Helper function to convert File to compressed base64 data URL for persistence
    const fileToDataURL = (file: File, maxWidth = 800, quality = 0.7): Promise<string> => {
        return new Promise((resolve, reject) => {
            const reader = new FileReader()
            reader.onload = () => {
                const img = new Image()
                img.onload = () => {
                    // Create canvas for compression
                    const canvas = document.createElement('canvas')
                    let { width, height } = img

                    // Scale down if larger than maxWidth
                    if (width > maxWidth) {
                        height = (height * maxWidth) / width
                        width = maxWidth
                    }

                    canvas.width = width
                    canvas.height = height

                    const ctx = canvas.getContext('2d')
                    if (!ctx) {
                        resolve(reader.result as string) // Fallback to original
                        return
                    }

                    ctx.drawImage(img, 0, 0, width, height)
                    // Convert to JPEG for better compression
                    const compressedDataUrl = canvas.toDataURL('image/jpeg', quality)
                    resolve(compressedDataUrl)
                }
                img.onerror = () => resolve(reader.result as string) // Fallback
                img.src = reader.result as string
            }
            reader.onerror = reject
            reader.readAsDataURL(file)
        })
    }

    const handleSave = async (formData: VehicleFormData) => {
        setIsSaving(true)

        // Generate stock ID first (needed for image paths)
        const stockId = await generateStockId()

        // Upload all photos to Supabase Storage
        // Si no hay fotos, usar placeholder "Próximamente"
        let imagenPrincipal = '/placeholder-proximamente.svg'
        const imagenesArray: { url: string; es_principal: boolean; orden: number }[] = []

        if (formData.fotos && formData.fotos.length > 0) {
            for (let i = 0; i < formData.fotos.length; i++) {
                const foto = formData.fotos[i]
                try {
                    const url = await uploadVehicleImage(foto.file, stockId, i)
                    const isPrincipal = formData.foto_principal === foto.id || (i === 0 && !formData.foto_principal)

                    imagenesArray.push({ url, es_principal: isPrincipal, orden: i })

                    if (isPrincipal) {
                        imagenPrincipal = url
                    }
                } catch (error) {
                    console.error('Error uploading image:', error)
                }
            }
        }

        // Create vehicle object for Supabase (without id, it will be generated by the database)
        const newVehicle: Omit<Vehicle, 'id'> = {
            vin: formData.vin || '',
            matricula: formData.matricula || '',
            stock_id: stockId,
            estado: 'disponible',
            destacado: formData.destacado ?? false,
            en_oferta: formData.en_oferta ?? false,
            marca: formData.marca,
            modelo: formData.modelo,
            version: formData.version || '',
            año_fabricacion: parseInt(formData.año_fabricacion) || parseInt(formData.año_matriculacion) || 2024,
            año_matriculacion: parseInt(formData.año_matriculacion) || 2024,
            mes_matriculacion: formData.mes_matriculacion ? parseInt(formData.mes_matriculacion) : undefined,
            tipo_motor: formData.combustible || 'gasolina',
            cilindrada: parseInt(formData.cilindrada) || 0,
            potencia_cv: parseInt(formData.potencia_cv) || 0,
            potencia_kw: Math.round((parseInt(formData.potencia_cv) || 0) * 0.7355),
            combustible: (formData.combustible || 'gasolina') as Vehicle['combustible'],
            consumo_mixto: 0,
            emisiones_co2: 0,
            etiqueta_dgt: 'C',
            transmision: (formData.transmision || 'manual') as Vehicle['transmision'],
            num_marchas: 5,
            traccion: 'delantera',
            tipo_carroceria: formData.tipo_carroceria || 'berlina',
            num_puertas: parseInt(formData.num_puertas) || 5,
            num_plazas: parseInt(formData.num_plazas) || 5,
            color_exterior: formData.color_exterior || '',
            color_interior: formData.color_interior || '',
            kilometraje: parseInt(formData.kilometraje) || 0,
            num_propietarios: parseInt(formData.num_propietarios) || 1,
            es_nacional: true,
            primera_mano: parseInt(formData.num_propietarios) === 1,
            precio_compra: parseFloat(formData.precio_compra) || 0,
            gastos_compra: parseFloat(formData.gastos_compra) || 0,
            coste_reparaciones: parseFloat(formData.coste_reparaciones) || 0,
            precio_venta: parseFloat(formData.precio_venta) || 0,
            descuento: parseFloat(formData.descuento) || 0,
            margen_bruto: (parseFloat(formData.precio_venta) || 0) - (parseFloat(formData.precio_compra) || 0) - (parseFloat(formData.gastos_compra) || 0) - (parseFloat(formData.coste_reparaciones) || 0),
            fecha_entrada_stock: new Date().toISOString().split('T')[0],
            dias_en_stock: 0,
            garantia_meses: parseInt(formData.garantia_meses) || 12,
            tipo_garantia: 'Garantía comercial',
            fecha_itv_vencimiento: formData.fecha_itv_vencimiento || undefined,
            imagen_principal: imagenPrincipal,
            imagenes: imagenesArray as any,
            descripcion: formData.descripcion || undefined,
            documentos: [],
            equipamiento: formData.equipamiento || [],
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            created_by: user?.id,
            created_by_name: profile ? `${profile.nombre} ${profile.apellidos}`.trim() : user?.email,
        }

        // Guardar en Supabase
        try {
            const savedVehicle = await createVehicle(newVehicle)
            if (savedVehicle) {
                // Disparar evento de actualización
                window.dispatchEvent(new CustomEvent('midcar-data-updated', { detail: { type: 'vehicles' } }))
                // Show success notification
                addToast(`Vehículo creado: ${formData.marca} ${formData.modelo}`, 'success')
            } else {
                throw new Error('No se pudo guardar el vehículo')
            }
        } catch (error) {
            console.error('Error saving vehicle:', error)
            addToast('Error al guardar el vehículo en la base de datos.', 'error')
            setIsSaving(false)
            return
        }

        setIsSaving(false)

        // Invalidar cache para que el inventario muestre el nuevo vehículo
        invalidateDataCache()

        // Redirect to inventory
        router.push('/inventario')
    }

    return (
        <div className="space-y-6 animate-in">
            <div className="flex items-center gap-4">
                <Link href="/inventario">
                    <Button variant="ghost" className="gap-2">
                        <ArrowLeft className="h-4 w-4" />
                        Volver
                    </Button>
                </Link>
                <div>
                    <h1 className="text-2xl font-bold text-foreground">Nuevo Vehículo</h1>
                    <p className="text-muted-foreground">Añade un nuevo vehículo al inventario</p>
                </div>
            </div>

            <VehicleForm
                onSubmit={handleSave}
                isSubmitting={isSaving}
            />
        </div>
    )
}

export default function NuevoVehiculoPage() {
    return (
        <Suspense fallback={
            <div className="flex items-center justify-center py-12">
                <div className="animate-spin rounded-full h-8 w-8 border-2 border-blue-500 border-t-transparent" />
            </div>
        }>
            <NuevoVehiculoContent />
        </Suspense>
    )
}
